### ISSUE TITLE
location is not right but still get normal ping and speed 

### ISSUE THREAD

**Issue by pollux56** [Ketok4321/speedtest#11]
i'm from australia
when doing a speedtest and choosing virginia, united states, ovh
i get 50ping and normal speeds like i would on a sydney or melbourne server but when i go to librespeed and choose virginia it gives me 700ping and terrible download and upload like it should
something is wrong with the text that's being displayed with the server, even tho its picking the right server for me lol
anyways i love the app and everything else seems to work rlly well :)

**Comment by Ketok4321** [comment]
Probably related to librespeed/speedtest#572

**Comment by pollux56** [comment]
> Probably related to librespeed/speedtest#572

Seems so, i will close this then thank you
